### ISSUE TITLE
[BUG] Record 추가 시 path에 대한 유효성 검사

### ISSUE THREAD

**Issue by seungyong** [seungyong/globa-backend#26]
## 어떤 버그가 발생했나요?
> 어떤 버그인지 간단하게 설명해주세요.

안드로이드에서 firebase에 업로드한 path에 대한 유효성 검사를 하지 않습니다.

## 버그를 재현하기 위한 순서를 작성해주세요.
> 요청 값, 헤더 형식, DB 데이터 등 버그가 발생하는 상황을 설명 또는 순서를 작성해주세요.

### API
URL : http://localhost:8080/folder/{folder_id}/record
path : /fakepath/123
size: 50
path에 대한 유효성 검사를 하지 않아, 불필요한 kafka 메시지 전송이 발생합니다.

## 기대 결과
> 정상적으로 이루어졌을 때 어떤 동작을 기대하고 있나요?

사용자가 보낸 path에 대한 유효성 검사 및 에러 반환

**Comment by dbstjdqls14** [comment]
엊그제 Commit에서 처리한 부분입니다. 머지 시, 해결됩니다.
